### ISSUE TITLE
How will published updates to the IG be versioned

### ISSUE THREAD

**Issue by Healthedata1** [HL7/US-Core#22]
based on:  http://build.fhir.org/versions.html

- The next technical update will be Release 1 (STU1) v1.0.1
- the next substantive update (PSS version) will be Release 1 (STU1) v1.1.0 
- a future R4 version would be Release 2 (STU2) v1.0.0

Where 'Release 1' = STU1  and  Release 2 = STU2

**Comment by brettmarquard** [comment]
We are developing a new release of US Core as 2.0.0 based on FHIR R4.
