### ISSUE TITLE
Invalid JSON in missing data example

### ISSUE THREAD

**Issue by tferullo** [HL7/US-Core#30]
Hi @brettmarquard noticed this when looking for information on Data Absent Reason. Happy to make a pull request if you'd like.

from US-Core-R4/source/pages/general-guidance.md:

```json
{
  "resourceType" : "Patient",
       ...
       "name":[
         "extension" : [
         "url" : "http://hl7.org/fhir/StructureDefinition/data-absent-reason",
         "valueCode" : "unknown"
          }]
          ]
        "telecom" :
        ...
     }
```

The actutal data absent reason extension above is invalid JSON. it should be:
```json
{
  "resourceType" : "Patient",
  ...
  "name":[{
    "extension" : [{
      "url" : "http://hl7.org/fhir/StructureDefinition/data-absent-reason",
      "valueCode" : "unknown"
    }]
  }]
  "telecom" :
  ...
}
```

**Comment by Healthedata1** [comment]
Yes please create a Jira tracker as a technical correction

**Comment by brettmarquard** [comment]
Thank you @tferullo. All Changes have to go through HL7 JIRA system -- see https://jira.hl7.org/. Let us know if you are able to log, if not, we will on your behalf.

**Comment by rlimosenero** [comment]
not sure whre to ask my question, but I'll try it here, may be you good guys can point me to sometihng. I am trying to implement the dataabsentreason(dar) in the diagnosticreport profile but I don't know how to put the code which will point to "issued" field".

Thanks in advance

**Comment by brettmarquard** [comment]
Please post these types of questions to zulip: https://chat.fhir.org/#narrow/stream/179175-argonaut

The prior issue here is fixed, so closing.

**Comment by rlimosenero** [comment]
Thanks!
